### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by noonosh** [bloomingjasmin/coding-lab#1]
Hey Jasmin,

It's your old friend from the lyceum. I have just looked into your project, and it's amazing! It felt so good when I found out on Instagram that u did a project, and since I am from a similar background (programming), I had a deep look into ur code, and it impressed me. Hope u still remember who I am.

[It's me!](https://read.nuriddinislamov.com/images/footer-about.jpeg)

Keep going, I am in love with what you are doing!

Bests,
Nuriddin

**Comment by bloomingjasmin** [comment]
> 

hey Nuriddin, haven't seen you for decades. hope you are doing well:)
So nice to hear warm words from you. Thank you !
